# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UlKe6jXf-Ae_KPRTpmrh9LAPppnfDeRy
"""

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
dat = pd.read_csv('train.csv')
dat.head()

dat.shape
dat.isnull().sum()

(dat.Survived == 0).sum()/((dat.Survived == 1).sum()+ (dat.Survived == 0).sum())

print((dat.Embarked == 'C').sum())
print((dat.Embarked == 'S').sum())
print((dat.Embarked == 'Q').sum())

dat.Age = dat.Age.fillna(0)
average = (dat.Age.sum())/(891-177)
for i in range(len(dat.Age)):
  if dat.Age[i] == 0  :
    dat.Age[i] = average
print(dat.Age)

#logistic regression#
map1 = dat.Sex
map2 = dat.Embarked
Sex_no = []
Embark_no = []
for i in range(len(map1)):
  if map1[i] == 'male':
    Sex_no.append(1)
  elif map1[i] =='female':
    Sex_no.append(0)
for i in range(len(map2)):
  if map2[i] == 'C':
    Embark_no.append(0)
  elif map2[i] =='S':
    Embark_no.append(1)
  elif map2[i] =='Q':
    Embark_no.append(2) 
  else :
    Embark_no.append(0.89)#NaN replaced with average of othe quantities
#print(Sex_no)
#dat2 is same as dat with Sex column replaced by integers
dat2 = dat.assign(Sex = Sex_no )
dat2 = dat2.assign(Embarked = Embark_no)
dat2.head()

print(set(dat.Cabin.fillna(0)))

X = dat2.drop("PassengerId",axis = 1)
X = X.drop("Survived",axis = 1)
X = X.drop("Name",axis = 1)
X = X.drop("Ticket",axis = 1)
X = X.drop("Cabin",axis = 1)
y = dat.Survived
from sklearn import preprocessing
X = preprocessing.normalize(X, norm='l2')
from sklearn.model_selection import train_test_split
X, x, Y, y = train_test_split(X, y, test_size=0.1)

from sklearn.linear_model import LogisticRegression
#X, Y = load_iris(return_X_y=True)
clf = LogisticRegression(solver ='lbfgs',max_iter = 200,random_state=0).fit(X, Y)
#x,y = load_iris(return_X_y=True)
clf.score(x,y)

tet =  pd.read_csv('test.csv')
tet.head()

print((tet.Embarked == 'C').sum())
print((tet.Embarked == 'S').sum())
print((tet.Embarked == 'Q').sum())

tet.shape

tet.isnull().sum()

tet.Age = tet.Age.fillna(0)
average = (tet.Age.sum())/(418-86)
for i in range(len(tet.Age)):
  if tet.Age[i] == 0  :
    tet.Age[i] = average
print(tet.Age)
tet.Fare = tet.Fare.fillna(0)
average = (tet.Fare.sum())/(418-1)
for i in range(len(tet.Fare)):
  if tet.Fare[i] == 0  :
    tet.Fare[i] = average
print(tet.Fare)

mape1 = tet.Sex
mape2 = tet.Embarked
Sex_no1 = []
Embark_no1 = []
for i in range(len(mape1)):
  if mape1[i] == 'male':
    Sex_no1.append(1)
  elif mape1[i] =='female':
    Sex_no1.append(0)
for i in range(len(mape2)):
  if mape2[i] == 'C':
    Embark_no1.append(0)
  elif mape2[i] =='S':
    Embark_no1.append(1)
  elif mape2[i] =='Q':
    Embark_no1.append(2)
tet2 = tet.assign(Sex = Sex_no1 )
tet2 = tet2.assign(Embarked = Embark_no1)
tet2.head()

X1 = tet2.drop("PassengerId",axis = 1)
X1 = X1.drop("Name",axis = 1)
X1 = X1.drop("Ticket",axis = 1)
X1 = X1.drop("Cabin",axis = 1)

X1.isnull().sum()
from sklearn import preprocessing
X1 = preprocessing.normalize(X1, norm='l2')
#from sklearn.datasets import load_iris
#X1 = load_iris(return_X_y=True)
ans = clf.predict(X1)

X1.head()

# Save Numpy array to csv
np.savetxt('array.csv', [ans], delimiter=',', fmt='%d')

df1 = pd.read_csv('test.csv')
df1.shape

ans.shape

df1["Survived"] = ans;

myans = df1[["PassengerId","Survived"]]

myans.to_csv('ans.csv', index = False)

!ls

from google.colab import files
files.download("ans.csv")

from google.colab import drive
drive.mount('drive')

from sklearn.datasets import load_iris
X,y = load_iris(return_X_y=True)

X

y